# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'


variables:
  buildConfiguration: 'Release'
  webRepository: 'web'
  tag: '$(Build.BuildId)'
     

stages:
- stage: 'Build'
  displayName: 'build the webapp'
  jobs:
  - job: 'Build'
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
    - task: Docker@2
      displayName: 'build and publish the container image'
      inputs:
        command: buildAndPush
        buildContext: $(Build.Repository.LocalPath)
        repository: $(webRepository)
        dockerfile: $(Build.SourcesDirectory)/Tailspin.Spacegame.Web/Dockerfile'
        containerRegistry: 'acr'
        tags: |
          $(tag)

- stage: 'Deployment'
  displayName: 'deploys the container to app services'
  dependsOn: 'Build'
  jobs:
  - job: 'Deploy'
    displayName: 'Depploy job'
    pool:
      vmImage: 'ubuntu-20.04'
    variables:
    - group: Release-docker
    steps:
    - task: AzureWebAppContainer@1
      inputs:
          appName: $(WebAppname) 
          azureSubscription: "test123"
          imageName: $(RegistryName/$(webRepository):$(build.buildId)
    